#!/usr/bin/env bash
# =============================================================================
# r1 - Single Command Bootstrap Script for Production VPS
# =============================================================================

set -Eeuo pipefail

cd / || true

APP_DIR="/var/www/r1"
APP_USER="r1-app"
RUNTIME_DIR="${APP_DIR}/runtime"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [BOOTSTRAP] $*"
}

log "=== Starting r1 Production Bootstrap ==="

# Update system
log "Updating system packages..."
apt-get update && apt-get upgrade -y

# Install dependencies
log "Installing required packages..."
apt-get install -y curl git nginx docker.io docker-compose-plugin

# Start Docker
log "Configuring Docker..."
systemctl enable --now docker

# Create app user
if ! id "$APP_USER" &>/dev/null; then
    log "Creating application user: $APP_USER"
    useradd -r -s /sbin/nologin -d "$APP_DIR" "$APP_USER"
fi

# Add to docker group
usermod -aG docker "${SUDO_USER:-$USER}" || true
usermod -aG docker "$APP_USER"

# Nginx setup - robust and non-blocking
log "Setting up Nginx reverse proxy..."

# Ensure runtime dir and placeholder always exist before any nginx operation
mkdir -p "$RUNTIME_DIR"
cat > "$RUNTIME_DIR/nginx-upstream.conf" << 'EOF'
# Placeholder generated by bootstrap - deploy.sh will update this
set $r1_backend http://127.0.0.1:5000;
EOF
chown -R "$APP_USER":"$APP_USER" "$RUNTIME_DIR"

# Create a clean site config
cat > /etc/nginx/sites-available/r1 << 'EOF'
server {
    listen 80 default_server;
    server_name _;

    include /var/www/r1/runtime/nginx-upstream.conf;

    location / {
        proxy_pass $r1_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /health {
        proxy_pass $r1_backend;
    }
}
EOF

ln -sf /etc/nginx/sites-available/r1 /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test config but do NOT fail bootstrap if nginx restart fails
if nginx -t; then
    log "Nginx config is valid. Restarting..."
    systemctl restart nginx || log "⚠️ Nginx restart failed but config is valid. Continuing..."
else
    log "⚠️ Nginx config test failed. Continuing bootstrap anyway."
fi

# Clone repo
log "Setting up application directory..."
mkdir -p "$APP_DIR"
if [ ! -d "$APP_DIR/.git" ]; then
    git clone https://github.com/mobin188/r1.git "$APP_DIR"
else
    cd "$APP_DIR" && git pull origin main
fi
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

# Scripts permissions
log "Setting execute permissions on deployment scripts..."
chmod +x "$APP_DIR/scripts/"*.sh

# .env setup
log "Setting up environment configuration..."
if [ ! -f "$APP_DIR/.env" ]; then
    cp "$APP_DIR/.env.example" "$APP_DIR/.env"
fi
# Generate SECRET_KEY
if ! grep -qE '^SECRET_KEY=.{20,}' "$APP_DIR/.env" || grep -q "your-super-secret-key-here" "$APP_DIR/.env"; then
    NEW_SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')
    sed -i "s|^SECRET_KEY=.*|SECRET_KEY=$NEW_SECRET|" "$APP_DIR/.env"
    log "✅ Generated strong SECRET_KEY"
fi
chown "$APP_USER":"$APP_USER" "$APP_DIR/.env"

# Nginx configuration (using set $var for safe include)
log "Setting up Nginx reverse proxy..."
cat > /etc/nginx/sites-available/r1 << 'EOF'
server {
    listen 80;
    server_name _;

    include /var/www/r1/runtime/nginx-upstream.conf;

    location / {
        proxy_pass $r1_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
EOF

ln -sf /etc/nginx/sites-available/r1 /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl restart nginx

# Initial deployment
log "Performing initial deployment..."
sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && ./scripts/deploy.sh latest"

log "✅ Bootstrap completed successfully!"
